package IPXACT2009ScalaCases

// Generated by <a href="http://IPXACT2009scalaxb.org/">IPXACT2009scalaxb</a>.


/** Base IP-XACT document reference type. Contains vendor, library, name and version attributes.
*/
case class LibraryRefType(attributes: Map[String, IPXACT2009scalaxb.DataRecord[Any]] = Map.empty) extends ViewTypeOption with GeneratorChainSelectorOption {
  lazy val vendor = attributes("@vendor").as[String]
  lazy val library = attributes("@library").as[String]
  lazy val name = attributes("@name").as[String]
  lazy val version = attributes("@version").as[String]
}

      
      


/** Resolved IP-XACT document reference type. Contains vendor, library, name and version attributes and the URI of the referenced IP-XACT document
*/
case class ResolvedLibraryRefType(value: java.net.URI,
  attributes: Map[String, IPXACT2009scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val vendor = attributes("@vendor").as[String]
  lazy val library = attributes("@library").as[String]
  lazy val name = attributes("@name").as[String]
  lazy val version = attributes("@version").as[String]
}

      
      

case class VersionedIdentifierSequence(vendor: String,
  library: String,
  name: String,
  version: String)
      

case class BaseIdentifierSequence()
      

/** Base IP-XACT document reference.  Contains vendor, library, name and version attributes.
*/
case class LibraryRefGroup(vendor: String,
  library: String,
  name: String,
  version: String)

