// Generated by <a href="http://IPXACT2022scalaxb.org/">IPXACT2022scalaxb</a>.
package IPXACT2022ScalaCases

case class SystemGroupName(value: String,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      


case class SystemGroupNames(systemGroupName: Seq[IPXACT2022ScalaCases.SystemGroupName] = Nil)
      
      


case class BusDefinition(documentNameGroupSequence1: IPXACT2022ScalaCases.DocumentNameGroupSequence,
  directConnection: Boolean,
  broadcast: Option[Boolean] = None,
  isAddressable: Boolean,
  extendsValue: Option[IPXACT2022ScalaCases.LibraryRefType] = None,
  maxInitiators: Option[IPXACT2022ScalaCases.UnsignedIntExpressionable] = None,
  maxTargets: Option[IPXACT2022ScalaCases.UnsignedIntExpressionable] = None,
  systemGroupNames: Option[IPXACT2022ScalaCases.SystemGroupNames] = None,
  choices: Option[IPXACT2022ScalaCases.Choices] = None,
  parameters: Option[IPXACT2022ScalaCases.Parameters] = None,
  assertions: Option[IPXACT2022ScalaCases.Assertions] = None,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) extends IPXACTDocumentTypesOption {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      

trait PortPropertiesOption1
