package IPXACT2009ScalaCases

// Generated by <a href="http://IPXACT2009scalaxb.org/">IPXACT2009scalaxb</a>.


case class SystemGroupNames(systemGroupName: Seq[String] = Nil)
      
      


case class BusDefinition(versionedIdentifierSequence1: VersionedIdentifierSequence,
  directConnection: Boolean,
  isAddressable: Boolean,
  extendsValue: Option[LibraryRefType] = None,
  maxMasters: Option[BigInt] = None,
  maxSlaves: Option[BigInt] = None,
  systemGroupNames: Option[SystemGroupNames] = None,
  description: Option[String] = None,
  vendorExtensions: Option[VendorExtensions] = None) extends IPXACTDocumentTypesOption
      
      

trait PortPropertiesOption1
