// Generated by <a href="http://IPXACT2022scalaxb.org/">IPXACT2022scalaxb</a>.
package IPXACT2022ScalaCases

/** This is the IP-XACT catalog definition
*/


/** Contains a list of IP-XACT files to include.
*/
case class IpxactFilesType(ipxactFile: Seq[IPXACT2022ScalaCases.IpxactFileType] = Nil)
      
      


case class Catalog(documentNameGroupSequence1: IPXACT2022ScalaCases.DocumentNameGroupSequence,
  catalogs: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  busDefinitions: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  abstractionDefinitions: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  components: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  abstractors: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  designs: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  designConfigurations: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  generatorChains: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  typeDefinitions: Option[IPXACT2022ScalaCases.IpxactFilesType] = None,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) extends IPXACTDocumentTypesOption {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      


case class IpxactFileType(vlnv: IPXACT2022ScalaCases.LibraryRefType,
  name: IPXACT2022ScalaCases.IpxactURIable,
  description: Option[String] = None,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      

