// Generated by <a href="http://IPXACT2022scalaxb.org/">IPXACT2022scalaxb</a>.
package IPXACT2022ScalaCases

/** Base IP-XACT document reference type. Contains vendor, library, name and version attributes.
*/
case class LibraryRefType(attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val vendor = attributes("@vendor").as[String]
  lazy val library = attributes("@library").as[String]
  lazy val name = attributes("@name").as[String]
  lazy val version = attributes("@version").as[String]
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      


/** Base IP-XACT document reference type for configurable top-level objects. Contains vendor, library, name and version attributes along with configurable element values.
*/
case class ConfigurableLibraryRefType(configurableElementValues: Option[IPXACT2022ScalaCases.ConfigurableElementValues] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) extends GeneratorChainSelectorOption {
  lazy val vendor = attributes("@vendor").as[String]
  lazy val library = attributes("@library").as[String]
  lazy val name = attributes("@name").as[String]
  lazy val version = attributes("@version").as[String]
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      

case class DocumentNameGroupSequence(versionedIdentifierSequence1: IPXACT2022ScalaCases.VersionedIdentifierSequence,
  displayName: Option[String] = None,
  shortDescription: Option[String] = None,
  description: Option[String] = None)
      

case class BaseIdentifierSequence()
      
case class VersionedIdentifierSequence(vendor: String,
  library: String,
  name: String,
  version: String)
      


/** Base IP-XACT document reference.  Contains vendor, library, name and version attributes.
*/
case class LibraryRefGroup(vendor: String,
  library: String,
  name: String,
  version: String,
  xmlid: Option[String] = None)

