// Generated by <a href="http://IPXACT2022scalaxb.org/">IPXACT2022scalaxb</a>.
package IPXACT2022ScalaCases

case class Mode2(nameGroupSequence1: IPXACT2022ScalaCases.NameGroupSequence,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      


case class Modes2(mode: Seq[IPXACT2022ScalaCases.Mode2] = Nil)
      
      


case class View4(nameGroupSequence1: IPXACT2022ScalaCases.NameGroupSequence,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      


case class Views3(view: Seq[IPXACT2022ScalaCases.View4] = Nil)
      
      


case class ResetType2(nameGroupSequence1: IPXACT2022ScalaCases.NameGroupSequence,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      


case class ResetTypes2(resetType: Seq[IPXACT2022ScalaCases.ResetType2] = Nil)
      
      


case class TypeDefinitions2(typedefinitions2sequence1: Option[IPXACT2022ScalaCases.TypeDefinitions2Sequence1] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) extends IPXACTDocumentTypesOption {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      

case class TypeDefinitions2Sequence1(documentNameGroupSequence1: IPXACT2022ScalaCases.DocumentNameGroupSequence,
  externalTypeDefinitions: Seq[IPXACT2022ScalaCases.ExternalTypeDefinitions] = Nil,
  modes: Option[IPXACT2022ScalaCases.Modes2] = None,
  views: Option[IPXACT2022ScalaCases.Views3] = None,
  fieldAccessPolicyDefinitions: Option[IPXACT2022ScalaCases.FieldAccessPolicyDefinitions] = None,
  enumerationDefinitions: Option[IPXACT2022ScalaCases.EnumerationDefinitions] = None,
  fieldDefinitions: Option[IPXACT2022ScalaCases.FieldDefinitions] = None,
  registerDefinitions: Option[IPXACT2022ScalaCases.RegisterDefinitions] = None,
  registerFileDefinitions: Option[IPXACT2022ScalaCases.RegisterFileDefinitions] = None,
  addressBlockDefinitions: Option[IPXACT2022ScalaCases.AddressBlockDefinitions] = None,
  bankDefinitions: Option[IPXACT2022ScalaCases.BankDefinitions] = None,
  memoryMapDefinitions: Option[IPXACT2022ScalaCases.MemoryMapDefinitions] = None,
  memoryRemapDefinitions: Option[IPXACT2022ScalaCases.MemoryRemapDefinitions] = None,
  resetTypes: Option[IPXACT2022ScalaCases.ResetTypes2] = None,
  choices: Option[IPXACT2022ScalaCases.Choices] = None,
  parameters: Option[IPXACT2022ScalaCases.Parameters] = None,
  assertions: Option[IPXACT2022ScalaCases.Assertions] = None,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None)
      

