// Generated by <a href="http://IPXACT2022scalaxb.org/">IPXACT2022scalaxb</a>.
package IPXACT2022ScalaCases

case class Design(documentNameGroupSequence1: IPXACT2022ScalaCases.DocumentNameGroupSequence,
  componentInstances: Option[IPXACT2022ScalaCases.ComponentInstances] = None,
  interconnections: Option[IPXACT2022ScalaCases.Interconnections] = None,
  adHocConnections: Option[IPXACT2022ScalaCases.AdHocConnections] = None,
  choices: Option[IPXACT2022ScalaCases.Choices] = None,
  parameters: Option[IPXACT2022ScalaCases.Parameters] = None,
  assertions: Option[IPXACT2022ScalaCases.Assertions] = None,
  vendorExtensions: Option[IPXACT2022ScalaCases.VendorExtensions] = None,
  attributes: Map[String, IPXACT2022scalaxb.DataRecord[Any]] = Map.empty) extends IPXACTDocumentTypesOption {
  lazy val xmlid = attributes.get("@{http://www.w3.org/XML/1998/namespace}id") map { _.as[String]}
}

      
      

