package IPXACT2009ScalaCases

// Generated by <a href="http://IPXACT2009scalaxb.org/">IPXACT2009scalaxb</a>.


case class HierConnection(interface: Interfacable,
  vendorExtensions: Option[VendorExtensions] = None,
  attributes: Map[String, IPXACT2009scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val interfaceRef = attributes("@interfaceRef").as[String]
}

      
      


case class HierConnections(hierConnection: Seq[HierConnection] = Nil)
      
      


case class Design(versionedIdentifierSequence1: VersionedIdentifierSequence,
  componentInstances: Option[ComponentInstances] = None,
  interconnections: Option[Interconnections] = None,
  adHocConnections: Option[AdHocConnections] = None,
  hierConnections: Option[HierConnections] = None,
  description: Option[String] = None,
  vendorExtensions: Option[VendorExtensions] = None) extends IPXACTDocumentTypesOption
      
      

